# Site settings
title: Tang Jiaze
email: ververcpp@gmail.com
name: Tang Jiaze
twitter: ververcpp
url:
description: "verver's blog based on Jekyll, Web, Computer & Life"

# Build settings
markdown: kramdown
permalink: pretty
